@startuml client-server architecture
top to bottom direction
node app as "               <b>Flashcard App\n<b>[Android application, providing\n<b>features to allow users create\n<b>and view flashacrads for study]\n"
cloud {
    database data as "          <b>Firestore Cloud Firebase \n<b>[stores user registration information\n<b>             and flashcard data]"
}
frame components{
    component auth as "         <b>Firebase Auth \n[External Auth system \n<b>that authenticates \n<b>and assign user access]"
    rectangle viewcard as "          <b>View deck\n<b>[Allows users to view\n<b>added services]"
    rectangle addcard as "                <b>Add cards\n<b>[Allows users to add new \n<b>cards to the deck]"
    rectangle home as "               <b>Home\n<b>[Displays the flashcards in \n<b>a Question-and-answer format\n"
    rectangle sign as "             <b>Sign-In\n<b>[Enforces access rights]"
    app ..> home :<b>Displays
    app ..> addcard : <b>Set up\n<b>parameters
    app ..> viewcard : <b>Set up\n<b>parameters
    app ..> sign : <b>Sends request
    home .right-> addcard: <b>Retrieved from
    viewcard .left-> addcard: <b>Retrieved from
    viewcard ..> data : <b>Data retrieved from\n<b>[JSON]
    sign ..> auth : <b>Authenticates\n<b>[HTTPS]
    home ..> data : <b>Data retrieved from\n<b>[JSON]
    auth ..> data : <b>Store data\n<b>[JSON]
    addcard ..> data : <b>Store data\n<b>[JSON]
}
@enduml